export const RSS_CNN_NEWS: string = 'https://www.cnnindonesia.com/{type}/rss'
export const RSS_CNBC_NEWS: string = 'https://www.cnbcindonesia.com/{type}/rss'
export const RSS_REPUBLIKA_NEWS: string = 'https://www.republika.co.id/rss/'
export const RSS_TEMPO_NEWS: string = 'http://rss.tempo.co/'
export const RSS_ANTARA_NEWS: string = 'https://www.antaranews.com/rss/'
export const RSS_KUMPARAN_NEWS: string = 'https://lapi.kumparan.com/v2.0/rss/'